-- Run this SQL in your Supabase project: SQL Editor > New query.
-- Creates tables for YourBuddy app: users, otp, user_profiles.

-- Users (login): username = normalized email, password_hash = salted hash
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- OTP for forgot-password: one row per identifier, replaced on new code
CREATE TABLE IF NOT EXISTS otp (
    identifier TEXT NOT NULL PRIMARY KEY,
    code TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);

-- User profiles (optional details; username references users.username)
CREATE TABLE IF NOT EXISTS user_profiles (
    username TEXT NOT NULL PRIMARY KEY REFERENCES users(username) ON DELETE CASCADE,
    name TEXT,
    age INTEGER,
    phone TEXT,
    blood_group TEXT,
    profile_photo TEXT,
    gender TEXT,
    bio TEXT,
    date_of_birth TEXT
);

-- profile_photo is stored as base64 text so it can be returned via JSON.
-- Optional: enable RLS and add policies if you use Supabase Auth later.
-- For app-only auth (password in users table), you can leave RLS disabled.

COMMENT ON TABLE users IS 'YourBuddy app users; username is normalized email';
COMMENT ON TABLE otp IS 'One-time codes for password reset';
COMMENT ON TABLE user_profiles IS 'Extended profile per user';
